using Specter.Rules.Builtin.Editors;
using Specter.Rules.Builtin.Rules;
using Specter.Rules.Builtin.Rules.Dsc;
using Specter.Configuration;
using Specter.Formatting;
using Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules;
using System;
using System.Collections.Generic;

namespace Specter.Rules.Builtin
{
    public static class BuiltinRules
    {
        public static IReadOnlyList<Type> DefaultRules { get; } = new[]
        {
            typeof(AlignAssignmentStatement),
            typeof(AvoidAssignmentToAutomaticVariable),
            typeof(AvoidDefaultTrueValueSwitchParameter),
            typeof(AvoidDefaultValueForMandatoryParameter),
            typeof(AvoidEmptyCatchBlock),
            typeof(AvoidExclaimOperator),
            typeof(AvoidGlobalAliases),
            typeof(AvoidGlobalFunctions),
            typeof(AvoidInvokingEmptyMembers),
            typeof(AvoidLongLines),
            typeof(AvoidReservedCharInCmdlet),
            typeof(AvoidReservedParams),
            typeof(AvoidUsingAllowUnencryptedAuthentication),
            typeof(AvoidSemicolonsAsLineTerminators),
            typeof(AvoidUsingBrokenHashAlgorithms),
            typeof(AvoidUsingComputerNameHardcoded),
            typeof(AvoidUsingDoubleQuotesForConstantString),
            typeof(AvoidUsingPlainTextForPassword),
            typeof(AvoidUserNameAndPasswordParams),
            typeof(AvoidGlobalVars),
            typeof(AvoidMultipleTypeAttributes),
            typeof(AvoidShouldContinueWithoutForce),
            typeof(AvoidNullOrEmptyHelpMessageAttribute),
            typeof(AvoidPositionalParameters),
            typeof(AvoidTrailingWhitespace),
            typeof(AvoidUsingCmdletAliases),
            typeof(AvoidUsingConvertToSecureStringWithPlainText),
            typeof(AvoidUsingInvokeExpression),
            typeof(AvoidUnsafeAddType),
            typeof(AvoidDangerousMethod),
            typeof(AvoidCommandInjection),
            typeof(AvoidDynamicMemberAccess),
            typeof(AvoidForeachObjectInjection),
            typeof(AvoidUnsafeEscaping),
            typeof(AvoidEmptyNamedBlocks),
            typeof(AvoidUnreachableCode),
            typeof(AvoidUnusedVariable),
            typeof(AvoidUsingUninitializedVariable),
            typeof(MeasureFunctionComplexity),
            typeof(AvoidVariableShadowing),
            typeof(AvoidNestedFunctions),
            typeof(AvoidProcessWithoutPipeline),
            typeof(AvoidBacktickContinuation),
            typeof(PreferTypeConstructor),
            typeof(AvoidNewObjectForPSCustomObject),
            typeof(AvoidSmartQuotes),
            typeof(AvoidFilterKeyword),
            typeof(AvoidUnsafeDeserialization),
            typeof(AvoidUsingWMICmdlet),
            typeof(AvoidUsingWriteHost),
            typeof(SuggestCmdletBinding),
            typeof(UseErrorActionPreferenceConsistently),
            typeof(MisleadingBacktick),
            typeof(PlaceCloseBrace),
            typeof(PlaceOpenBrace),
            typeof(PossibleIncorrectComparisonWithNull),
            typeof(PossibleIncorrectUsageOfAssignmentOperator),
            typeof(PossibleIncorrectUsageOfRedirectionOperator),
            typeof(UseLiteralInitializerForHashtable),
            typeof(UseConsistentIndentation),
            typeof(UseConsistentWhitespace),
            typeof(UseCorrectCasing),
            typeof(UseDeclaredVarsMoreThanAssignments),
            typeof(UsePSCredentialType),
            typeof(UseProcessBlockForPipelineCommand),
            typeof(UseApprovedVerbs),
            typeof(UseShouldProcessForStateChangingFunctions),
            typeof(AvoidOverwritingBuiltInCmdlets),
            typeof(AvoidReservedWordsAsFunctionNames),
            typeof(UseBOMForUnicodeEncodedFile),
            typeof(UseUTF8EncodingForHelpFile),
            typeof(UseUsingScopeModifierInNewRunspaces),
            typeof(ReviewUnusedParameter),
            typeof(UseSingularNouns),
            typeof(UseSupportsShouldProcess),
            typeof(AvoidUsingDeprecatedManifestFields),
            typeof(UseCompatibleSyntax),
            typeof(UseCompatibleCmdlets),
            typeof(UseCompatibleCommands),
            typeof(UseToExportFieldsInManifest),
            typeof(MissingModuleManifestField),
            typeof(ProvideCommentHelp),
            typeof(UseShouldProcessCorrectly),
            typeof(UseOutputTypeCorrectly),
            typeof(UseCmdletCorrectly),
            typeof(UseStandardDscFunctionsInResource),
            typeof(UseVerboseMessageInDscResource),
            typeof(ReturnCorrectTypesForDscFunctions),
            typeof(UseIdenticalParametersDsc),
            typeof(DscTestsPresent),
            typeof(DscExamplesPresent),
            typeof(UseIdenticalMandatoryParametersDsc),
        };
    }

    public static class Default
    {
        private static IEditorConfiguration DisabledEditorConfig<T>() where T : IEditorConfiguration, new()
        {
            var config = new T();
            config.Common.Enable = false;
            return config;
        }

        public static IReadOnlyDictionary<string, IRuleConfiguration?> RuleConfiguration { get; } = new Dictionary<string, IRuleConfiguration?>(StringComparer.OrdinalIgnoreCase)
        {
            { "PS/AlignAssignmentStatement", DisabledEditorConfig<AlignAssignmentStatementEditorConfiguration>() },
            { "PS/AvoidDefaultValueForMandatoryParameter", null },
            { "PS/AvoidDefaultValueSwitchParameter", null },
            { "PS/AvoidExclaimOperator", new AvoidExclaimOperatorConfiguration { Common = new CommonConfiguration(enable: false) } },
            { "PS/AvoidGlobalAliases", null },
            { "PS/AvoidGlobalFunctions", null },
            { "PS/AvoidMultipleTypeAttributes", null },
            { "PS/AvoidNullOrEmptyHelpMessageAttribute", null },
            { "PS/AvoidTrailingWhitespace", null },
            { "PS/AvoidUsingCmdletAliases", null },
            { "PS/AvoidUsingConvertToSecureStringWithPlainText", null },
            { "PS/AvoidUsingEmptyCatchBlock", null },
            { "PS/AvoidUsingInvokeExpression", new AvoidUsingInvokeExpressionConfiguration() },
            { "PS/AvoidUnsafeAddType", null },
            { "PS/AvoidDangerousMethod", null },
            { "PS/AvoidCommandInjection", null },
            { "PS/AvoidDynamicMemberAccess", new CommonConfiguration(enable: false) },
            { "PS/AvoidForeachObjectInjection", null },
            { "PS/AvoidUnsafeEscaping", null },
            { "PS/AvoidEmptyNamedBlocks", null },
            { "PS/AvoidUnreachableCode", null },
            { "PS/AvoidUnusedVariable", null },
            { "PS/AvoidUsingUninitializedVariable", null },
            { "PS/MeasureFunctionComplexity", new MeasureFunctionComplexityConfiguration() },
            { "PS/AvoidVariableShadowing", new AvoidVariableShadowingConfiguration { Common = new CommonConfiguration(enable: false) } },
            { "PS/AvoidNestedFunctions", null },
            { "PS/AvoidProcessWithoutPipeline", null },
            { "PS/AvoidBacktickContinuation", new CommonConfiguration(enable: false) },
            { "PS/PreferTypeConstructor", new CommonConfiguration(enable: false) },
            { "PS/AvoidNewObjectForPSCustomObject", null },
            { "PS/AvoidSmartQuotes", null },
            { "PS/AvoidFilterKeyword", new CommonConfiguration(enable: false) },
            { "PS/AvoidUnsafeDeserialization", null },
            { "PS/AvoidUsingAllowUnencryptedAuthentication", null },
            { "PS/AvoidUsingWriteHost", null },
            { "PS/SuggestCmdletBinding", null },
            { "PS/UseErrorActionPreferenceConsistently", null },
            { "PS/AvoidAssignmentToAutomaticVariable", null },
            { "PS/AvoidInvokingEmptyMembers", null },
            { "PS/AvoidLongLines", new AvoidLongLinesConfiguration { Common = new CommonConfiguration(enable: false) } },
            { "PS/AvoidSemicolonsAsLineTerminators", new CommonConfiguration(enable: false) },
            { "PS/AvoidUsingBrokenHashAlgorithms", null },
            { "PS/AvoidUsingDoubleQuotesForConstantString", new CommonConfiguration(enable: false) },
            { "PS/AvoidUsingComputerNameHardcoded", null },
            { "PS/AvoidUsingPlainTextForPassword", null },
            { "PS/AvoidUsingUsernameAndPasswordParams", null },
            { "PS/AvoidGlobalVars", null },
            { "PS/AvoidShouldContinueWithoutForce", null },
            { "PS/AvoidUsingPositionalParameters", new AvoidPositionalParametersConfiguration() },
            { "PS/AvoidUsingWMICmdlet", null },
            { "PS/PossibleIncorrectUsageOfAssignmentOperator", null },
            { "PS/PossibleIncorrectUsageOfRedirectionOperator", null },
            { "PS/UseLiteralInitializerForHashtable", null },
            { "PS/UsePSCredentialType", null },
            { "PS/MisleadingBacktick", null },
            { "PS/PlaceCloseBrace", DisabledEditorConfig<PlaceCloseBraceEditorConfiguration>() },
            { "PS/PlaceOpenBrace", DisabledEditorConfig<PlaceOpenBraceEditorConfiguration>() },
            { "PS/PossibleIncorrectComparisonWithNull", null },
            { "PS/ReservedCmdletChar", null },
            { "PS/ReservedParams", null },
            { "PS/UseConsistentIndentation", DisabledEditorConfig<UseConsistentIndentationEditorConfiguration>() },
            { "PS/UseConsistentWhitespace", DisabledEditorConfig<UseConsistentWhitespaceEditorConfiguration>() },
            { "PS/UseCorrectCasing", DisabledEditorConfig<UseCorrectCasingEditorConfiguration>() },
            { "PS/UseApprovedVerbs", null },
            { "PS/UseDeclaredVarsMoreThanAssignments", null },
            { "PS/UseProcessBlockForPipelineCommand", null },
            { "PS/UseShouldProcessForStateChangingFunctions", null },
            { "PS/AvoidOverwritingBuiltInCmdlets", new AvoidOverwritingBuiltInCmdletsConfiguration() },
            { "PS/AvoidReservedWordsAsFunctionNames", null },
            { "PS/UseBOMForUnicodeEncodedFile", null },
            { "PS/UseUTF8EncodingForHelpFile", null },
            { "PS/UseUsingScopeModifierInNewRunspaces", null },
            { "PS/ReviewUnusedParameter", new ReviewUnusedParameterConfiguration() },
            { "PS/UseSingularNouns", new UseSingularNounsConfiguration() },
            { "PS/UseSupportsShouldProcess", null },
            { "PS/AvoidUsingDeprecatedManifestFields", null },
            { "PS/UseCompatibleSyntax", new UseCompatibleSyntaxConfiguration() },
            { "PS/UseCompatibleCmdlets", new UseCompatibleCmdletsConfiguration() },
            { "PS/UseCompatibleCommands", new UseCompatibleCommandsConfiguration() },
            { "PS/UseToExportFieldsInManifest", null },
            { "PS/MissingModuleManifestField", null },
            { "PS/ProvideCommentHelp", new ProvideCommentHelpConfiguration() },
            { "PS/ShouldProcess", null },
            { "PS/UseOutputTypeCorrectly", null },
            { "PS/UseCmdletCorrectly", null },
            { "PSDSC/StandardDSCFunctionsInResource", null },
            { "PSDSC/UseVerboseMessageInDSCResource", null },
            { "PSDSC/ReturnCorrectTypesForDSCFunctions", null },
            { "PSDSC/UseIdenticalParametersForDSC", null },
            { "PSDSC/DscTestsPresent", null },
            { "PSDSC/DscExamplesPresent", null },
            { "PSDSC/UseIdenticalMandatoryParametersForDSC", null },
        };

    }

}
